env:
    GITHUB_TOKEN: ENCRYPTED[7ff8738ddc83e13bc39482c3efe7d29da41ccd0716e6a89e25fe860babadeafd6020616ca632ccdb87222a1de387ea75]
    
    # Cirrus Specific Vars (Do *NOT* Change)
    CIRRUS_SHELL: bash

task:
  name: "Recovery Build"
  timeout_in: 120m
  container:
      image: ghcr.io/sushrut1101/docker:arch
      cpu: 8
      memory: 32G

  clone_script:
      - curl -sL https://raw.githubusercontent.com/LeeXDA21/CI-Scripts/shrp/clone.sh | bash

  building_script:
      - curl -sL https://raw.githubusercontent.com/LeeXDA21/CI-Scripts/shrp/building.sh | bash

  Upload_script:
      - curl -sL https://raw.githubusercontent.com/LeeXDA21/CI-Scripts/shrp/upload.sh | bash

  Upload2_script:
      - curl -sL https://raw.githubusercontent.com/LeeXDA21/CI-Scripts/shrp/upload2.sh | bash

